This is makeindex, version 2.15 [MiKTeX 2.9.6650] (kpathsea + Thai support).
Scanning style file ./polacek.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file polacek.acn....done (9 entries accepted, 0 rejected).
Sorting entries....done (29 comparisons).
Generating output file polacek.acr....done (26 lines written, 0 warnings).
Output written in polacek.acr.
Transcript written in polacek.alg.
